package model;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.Required;

public class User extends RealmObject  {

    @Required
    private String          name;

    @Required
    private String          email;

    @Required
    private String        userid;
    private int             age;

    @Ignore
    private int             sessionId;

    // Standard getters & setters generated by your IDE…


    public User() {

    }

    public User(String name, String email, String userid) {
        this.name = name;
        this.email = email;
        this.userid = userid;
    }
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public int    getAge() { return age; }
    public void   setAge(int age) { this.age = age; }
    public int    getSessionId() { return sessionId; }
    public void   setSessionId(int sessionId) { this.sessionId = sessionId; }
    public String getEmail() { return email; }


}